#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS1Ob5S273g29ujJl2Lp74ekkNPORBXPijZN"
APP_SECRET: "a0WC4fTlfyHvoS/QCiR5koHN3Z3uK5oonjod+cUx84NzRTDc/rLRvBaeXL8UiLvyjCDNX+E1yqjpIfZrd/wVzN/QzAnaeXCDUbmM1Cnw2mnO5gyngM22u2S1hkXlaWmNPvJEEs1tEinnD3r3rNixY8r6bt/FOP/XLyOen52nYRX56JDG0B8="

#계좌번호 앞 8자리
CANO: "50069528"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1004031912005877770/NZDaXbl0tIQIMnxydYjXBtzLyPVCTB5Qmogo4KglxbTHOmlT4OC0w1ksvyhMLPZ0_15c"